#!/usr/bin/env zsh
## configuration file for devuan-desktop-live blend

vars+=(username userpass default_shell mkefi grubversion hookscripts)
arrs+=(custom_deb_packages)

blend_name="acheros"
release="excalibur"
version="6.1.1"
username="acheros"
userpass="acheros"
default_shell="/bin/bash"

# comment to disable:
#hookscripts="yes"

arch="amd64"
#arch="i386"

case "$arch" in
        # for minimal-live
        #i386)  extra_packages+=(linux-image-686) ;;
 
        # for desktop-live
	i386)  # extra_packages+=(linux-image-686-pae)
		memtestarch="ia32" ;;

	amd64) # extra_packages+=(linux-image-amd64)
		memtestarch="x64" ;;
esac


# uncomment to create uefi-bootable iso
MKEFI=1
efi_work="$BLENDPATH/${release}/efi-files"

#grubversion="grub-pc"
grubversion="grub-efi-amd64"

# Uncomment for amd64
base_packages+=(grub-efi-amd64-bin grub-efi-ia32-bin shim-signed)

mirror="http://pkgmaster.devuan.org/merged"
section="main non-free-firmware non-free contrib"


base_packages_option=(--no-install-recommends)
extra_packages_option=(--no-install-recommends)


release_conf="$BLENDPATH/${release}/config"


### package sets are defined in the corresponding $release/config file

source $release_conf

## image_name depends on release and version

image_name="${os}_${release}_${version}_${arch}_desktop"
