# Core options ─────────────────────────────────────────────────────────────────
[core]
plugins = \
  animate \
  autostart \
  command \
  decoration \
  expo \
  fast-switcher \
  foreign-toplevel \
  grid \
  gtk-shell \
  move \
  place \
  resize \
  session-lock \
  shortcuts-inhibit \
  switcher \
  wayfire-shell \
  wm-actions \
  wsets \
  wrot

close_top_view = <super> KEY_Q | <alt> KEY_F4
vwidth = 3
vheight = 3
preferred_decoration_mode = server

[input]
cursor_theme = Planchette
xkb_layout = us,il
xkb_options = grp:alt_shift_toggle,caps:escape
touchpad_accel_profile = adaptive
mouse_cursor_speed = 1
scroll_method = two-finger
middle_emulation = true
natural_scroll = true
disable_touchpad_while_typing = true

[move]
enable_snap = false
activate = <super> BTN_LEFT

[resize]
activate = <super> <shift> BTN_LEFT

[wrot]
activate = <super> <ctrl> BTN_LEFT
activate-3d = <super> <alt> BTN_LEFT
reset-one = <super> KEY_R

[autostart]
0_env = dbus-update-activation-environment --all WAYLAND_DISPLAY DISPLAY XAUTHORITY
quickstart = alacritty --command tmux new-session quickstart
background = swaybg -i ~/.config/wayfire/background.png
panel = waybar
portal = /usr/libexec/xdg-desktop-portal
gtk-theme =    gsettings set org.gnome.desktop.interface gtk-theme Material-Black-Plum
theme =        gsettings set org.gnome.desktop.wm.preferences theme Material-Black-Plum
icon-theme =   gsettings set org.gnome.desktop.interface icon-theme MB-Plum-Suru-GLOW
cursor-theme = gsettings set org.gnome.desktop.interface cursor-theme Planchette

# Applications ─────────────────────────────────────────────────────────────────
[command]
binding_terminal = <super> KEY_ENTER
command_terminal = alacritty

binding_lock = <super> <shift> KEY_ESC
command_lock = swaylock

repeatable_binding_volume_up = KEY_VOLUMEUP
command_volume_up = amixer set Master 5%+
repeatable_binding_volume_down = KEY_VOLUMEDOWN
command_volume_down = amixer set Master 5%-
binding_mute = KEY_MUTE
command_mute = amixer set Master toggle

repeatable_binding_light_up = KEY_BRIGHTNESSUP
command_light_up = brightnessctl -c backlight s 10%+
repeatable_binding_light_down = KEY_BRIGHTNESSDOWN
command_light_down = brightnessctl -c backlight s 5%-

[wm-actions]
toggle_fullscreen = <super> KEY_F
toggle_always_on_top = <super> KEY_X
toggle_sticky = <super> <shift> KEY_X

[grid]
# ⇱ ↑ ⇲   │ 7 8 9
# ← f →   │ 4 5 6
# ⇱ ↓ ⇲ d │ 1 2 3 0
slot_bl = <super> KEY_KP1
slot_b = <super> KEY_KP2
slot_br = <super> KEY_KP3
slot_l = <super> KEY_LEFT | <super> KEY_KP4
slot_c = <super> KEY_UP | <super> KEY_KP5
slot_r = <super> KEY_RIGHT | <super> KEY_KP6
slot_tl = <super> KEY_KP7
slot_t = <super> KEY_KP8
slot_tr = <super> KEY_KP9
restore = <super> KEY_DOWN | <super> KEY_KP0

[fast-switcher]
activate = <alt> KEY_TAB

[expo]
toggle = <super> KEY_E

[invert]
toggle = <super> KEY_I

[wayfire-shell]
toggle_menu = <super>

[animate]
close_animation = fire
open_animation = fire
startup_animation = fire
duration = 0.2s
ccc
fire_color = 0.7 0.14 0.9 0.9

[decoration]
title_height = 0
ignore_views = none
border_size = 2
active_color = 1.0 0.14 1.0 1.0
inactive_color = 0.35 0.07 0.45 0.6
dynamic_border_colorr= true

[winshadows]
glow_enabled = true
shadow_radius = 50
vertical_offset = 10
horizontal_offset = 5

[workarounds]
force_preferred_decoration_mode = true
