---
userGroup:       users
defaultGroups:
    - audio
    - bluetooth
    - cdrom
    - dip
    - floppy
    - input
    - lpadmin
    - netdev
    - nix-users
    - plugdev
    - scanner
    - sudo
    - video
autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: false

passwordRequirements:
    nonempty: true
    minLength: -1  # Password at least this many characters
    maxLength: -1  # Password at most this many characters
    libpwquality:
        - minlen=0
        - minclass=0

